# build stage
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . . 

RUN npm run build

# Production stage
FROM node:22-alpine 

WORKDIR /app

RUN npm i -g serve

ENV PATH="/usr/local/bin:$PATH"

COPY --from=build /app/dist ./dist

EXPOSE 5174

CMD ["serve", "-s","dist", "-l","5174"]